### ISSUE TITLE
Change password using mod_register in ejabberd

### ISSUE THREAD

**Issue by iammehrabalam** [fritzy/SleekXMPP#427]
I am using ejabberd in a project for instant messaging. For user registration i am using mod_register module(in sleekxmpp). I am able to register user using mod_register module but not able to change password.

My use case if user not register with username in iq stanza then create and if user already exist than update password only.

Note: don't know user old password

for change password IQ (docs xep-0077)

```
<iq type="set" id="6120eace-8349-4853-a37e-2e4f85cdb5f4-2">
    <query xmlns="jabber:iq:register">
       <username>user1</username>
       <password>password1</password>
    </query>
</iq>
```

Response

```
<iq type="error" from="domain" id="6120eace-8349-4853-a37e-2e4f85cdb5f4-2">
      <query xmlns="jabber:iq:register">
         <username>user1</username>
         <password>password1</password>
      </query>
      <error code="409" type="cancel"><conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">User already exists</text>
      </error>
</iq>
```

config for mod_register in ejabberd.yml

```
acl:
  loopback:
    ip:
      - "ip-address"

access_rules:
  mynetworks:
    - allow: loopback
  register:
    - allow: all

modules:
  mod_register:
    ip_access: mynetworks
    access: register
```

ejabberd docs not helping.

How to update or change password using mod_register plugin in sleekxmpp
